
# Setup OS
FROM ubuntu

# Update repositories
RUN apt update -y
RUN apt upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa

# Install Python3.10
RUN apt install python3.10
